name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Install Tauri CLI
        run: cargo install tauri-cli
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Build frontend
        run: pnpm build
        
      - name: Build Tauri app
        run: cargo tauri build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: src-tauri/target/release/*.exe 